name: Build and Push Dockerimage
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-java@v1
        with:
          java-version: 1.9
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assemble with Gradle
        run: ./gradlew assemble

      - name: Publish to Registry
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: jekyll2cms/blogpost-checker
          tag: 1.0.3
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
